### ISSUE TITLE
New podcasts

### ISSUE THREAD

**Issue by fdaniele85** [manmatteo/postcast#2]
In January, several podcasts will become subscriber-only. Will you be adding them? I'd like to help you, but I don't understand how you get the podcast id, if you tell me I could make the change and a pull request.

**Comment by manmatteo** [comment]
Grazie per avermelo ricordato! In passato c’era un modo semplice per ottenere gli id dalla pagina del podcast, e li recuperavo col codice che legge quella pagina. Ora invece sono presenti solo nella pagina che gli elenca tutti, e non ho ancora scritto codice per analizzarla. Da quando hanno fatto quel cambio, ho semplicemente trascritto a mano i dati che avevo già.

Mi ero ripromesso di rendere tutto più generico e recuperare in automatico tutto i podcast dalla lista, ma non ho ancora trovato il tempo per farlo. Nei prossimi giorni se non trovo niente di meglio sistemo manualmente!
